##PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [90]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensors()` = https://pytorch.org/docs/stable/tensors.html

In [91]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [92]:
scalar.ndim

0

In [93]:
#Get tensor back as Python int
scalar.item()

7

In [94]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [95]:
vector.ndim

1

In [96]:
vector.shape

torch.Size([2])

In [97]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                        [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [98]:
MATRIX.ndim

2

In [99]:
MATRIX[1]

tensor([ 9, 10])

In [100]:
MATRIX.shape

torch.Size([2, 2])

In [101]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 8]]])

In [102]:
TENSOR.ndim

3

In [103]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

why random tensors?

Random tensors are important because the way many neural netwoks learn is that they start with tensors full of random numbers and then adjust those random  numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [104]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]],

        [[0.1053, 0.2695, 0.3588, 0.1994],
         [0.5472, 0.0062, 0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090]]])

In [105]:
random_tensor.ndim

3

In [106]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # height, width, colour channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [107]:
# Ceate a tensor of all zeros
zeros = torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [108]:
# Ceate a tensor of alll ones
ones = torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [109]:
ones.dtype

torch.float32

In [110]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [111]:
# Use torch.arange()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
# Use torch.arange() with steps as third parameter
torch.arange(start=0,end=10,step=2)

tensor([0, 2, 4, 6, 8])

In [113]:
# Create tensors like
ten_zeros = torch.zeros_like(torch.arange(0,10))
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatype

**Note:** Tensor datatypes is one of the 3 big errors with pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [114]:
#Float 32 tensor
f_32_tensor = torch.tensor([3.0,6.0,9.0],
                           dtype=None)
f_32_tensor

tensor([3., 6., 9.])

In [115]:
f_32_tensor.dtype

torch.float32

In [116]:
f_32_tensor = torch.tensor([3.0,6.0,9.0],
                           dtype=torch.float16,
                           device=None,# its value can be "cpu", "cuda" etc.
                           requires_grad=False)# weather or not to track gradients with this tensors operations
f_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [117]:
f_32_tensor.dtype

torch.float16

In [118]:
f_16_tensor = f_32_tensor.type(torch.float16)
f_16_tensor,f_32_tensor

(tensor([3., 6., 9.], dtype=torch.float16),
 tensor([3., 6., 9.], dtype=torch.float16))

In [119]:
f_16_tensor*f_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [120]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [121]:
f_32_tensor*int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from a tensor, can use `tensor.device`

In [122]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1336, 0.9666, 0.9754, 0.8474],
        [0.8988, 0.1105, 0.4563, 0.9719],
        [0.3968, 0.1496, 0.4743, 0.9973]])

In [123]:
#Find details about some tensor
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
cpu


`tensor.shape == tensor.size()`

### Manipulating tensors (tensr operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [124]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [125]:
# Create a tensor and multiply 10 to it
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [126]:
tensor

tensor([1, 2, 3])

In [127]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [128]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication
* Element-wise Multiplication
* Matrix multiplication (dot product)


In [129]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [130]:
tensor @ tensor

tensor(14)

In [131]:
# Matrix multiplication
%%time
torch.matmul(tensor,tensor)

CPU times: user 440 µs, sys: 33 µs, total: 473 µs
Wall time: 386 µs


tensor(14)

In [132]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 796 µs, sys: 0 ns, total: 796 µs
Wall time: 1.73 ms


### One of the most common errors in deep learning: shape error

In [133]:
# Shapes for Matrix multiplication
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_b = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
#torch.mm is an alias for torch.matmul
torch.mm(tensor_a,tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

To fix our tensor shape issues, we can manipulate the shape of the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimension of a given tensor.

In [134]:
tensor_b.T, tensor_b

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [135]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [136]:
#Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [137]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [138]:
#Find the mean - note: the torch.mean() function requires a tensor of float32 datatypeto work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [139]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [140]:
# Find index of max value
x.argmax()

tensor(9)

## Reshaping, Stacking, squeezing and unsqueezing tensors

* Reshapeing - reshapes an input tensor to a defined shape
* View - Return a view oa an input tensor of certain shape but keep the memory as original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimension from the tensor
* Unsqueeze - add a `1` dimension to the target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [141]:
import torch
x=torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [142]:
# Add an extra dimension
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [143]:
# Change the view
z = x_reshaped.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [144]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0]=5
z,x_reshaped

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([[ 5.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]))

In [145]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [146]:
# torch.squeeze() - remove all single dimensions from a target tensor
x

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [147]:
x.shape

torch.Size([10])

In [148]:
x.squeeze()

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [149]:
x.squeeze().shape

torch.Size([10])

In [150]:
y = torch.rand(2,3,4,5)
y.squeeze().shape

torch.Size([2, 3, 4, 5])

In [151]:
y = torch.rand(2,3,1)
print(y)
print(y.squeeze().shape)
print(y.squeeze())# on using this function it does not affect acctual tensor that is saved in memory it is just like a view after squeezing
print(y)

tensor([[[0.2319],
         [0.2378],
         [0.2206]],

        [[0.4074],
         [0.9057],
         [0.4490]]])
torch.Size([2, 3])
tensor([[0.2319, 0.2378, 0.2206],
        [0.4074, 0.9057, 0.4490]])
tensor([[[0.2319],
         [0.2378],
         [0.2206]],

        [[0.4074],
         [0.9057],
         [0.4490]]])


In [152]:
# troch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(y.unsqueeze(dim=-1).shape)
print(y.unsqueeze(dim=-1)) # here dim specify the index in the shape vector to add new dimension of 1

torch.Size([2, 3, 1, 1])
tensor([[[[0.2319]],

         [[0.2378]],

         [[0.2206]]],


        [[[0.4074]],

         [[0.9057]],

         [[0.4490]]]])


In [153]:
# torch.permute(input, dims) - Returns a view of the original tensor input with its dimensions permuted
x_original = torch.rand(size=(224,224,3))

x_permute = x_original.permute(2,0,1)# shift axis 0->1, 1->2, 2->0

x_original.shape, x_permute.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [154]:
print(x_original,x_original[0,:,0])

tensor([[[0.6509, 0.7044, 0.5421],
         [0.0280, 0.4097, 0.2592],
         [0.6951, 0.7100, 0.8263],
         ...,
         [0.0591, 0.2345, 0.2016],
         [0.7638, 0.3896, 0.5299],
         [0.1507, 0.4263, 0.2816]],

        [[0.5781, 0.2893, 0.1218],
         [0.5544, 0.7377, 0.2036],
         [0.9718, 0.2110, 0.4500],
         ...,
         [0.4151, 0.7915, 0.3596],
         [0.9970, 0.5229, 0.9105],
         [0.7823, 0.9284, 0.6485]],

        [[0.6766, 0.4927, 0.3779],
         [0.0620, 0.2756, 0.9624],
         [0.9886, 0.1290, 0.3393],
         ...,
         [0.6547, 0.6264, 0.5410],
         [0.8486, 0.1014, 0.9861],
         [0.6656, 0.7579, 0.9305]],

        ...,

        [[0.6408, 0.9971, 0.4971],
         [0.6439, 0.6868, 0.4919],
         [0.3138, 0.4212, 0.9657],
         ...,
         [0.7576, 0.3536, 0.4897],
         [0.6165, 0.6483, 0.8948],
         [0.0973, 0.5590, 0.3880]],

        [[0.7332, 0.6768, 0.5422],
         [0.1895, 0.8531, 0.2947],
         [0.

In [155]:
x_original[0,1,0]=12345
x_permute[0,0,1]

tensor(12345.)

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [156]:
# Create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [157]:
# let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [158]:
# let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [159]:
# let's index on the innermost bracket (dim=2)
x[0][0][0]

tensor(1)

In [160]:
x[0,:,2]

tensor([3, 6, 9])

## PyTorch Tensors & NumPy

NumPy is a popular  scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [161]:
#Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)# warning: when converting from numpy -> pytorch, pytorch refelects nupy a default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [162]:
# Change the value of array
array=array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [163]:
#Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [164]:
# Change the value of tensor
tensor=tensor+1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again...`
To reduce the randomness in neural networks annd PyTorch the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

In [165]:
import torch

# Create two random tensors
r_t_a = torch.rand(3,4)
r_t_b = torch.rand(3,4)
r_t_a,r_t_b,r_t_a==r_t_b

(tensor([[0.2946, 0.4927, 0.1327, 0.3688],
         [0.6080, 0.8430, 0.2695, 0.3086],
         [0.9538, 0.6358, 0.2506, 0.3042]]),
 tensor([[0.7766, 0.7982, 0.0143, 0.0716],
         [0.5590, 0.3050, 0.0025, 0.4465],
         [0.6931, 0.1049, 0.1234, 0.2569]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [166]:
# let's make some random but reproducable tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)#it only works for the first next line of code where it has a use
random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

random_tensor_c, random_tensor_d, random_tensor_c==random_tensor_d

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

Extra resource for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computation)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scene to make everything hunky dory(good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU
3. Use Cloud Computing - GCP, AWS, Azure, these services alloe you to rent computer on the cloud and access them

In [179]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### 2. Check for GPU access with PyTorch

In [168]:
import torch
torch.cuda.is_available()

False

For Pytorch since it's capable of running copute on the GPU or CPU, it's best practice to setup device agnostic code:https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [169]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [170]:
# count number of devices
torch.cuda.device_count()

0

## 3. Putting tensors and the models on the GPU

To get faster computations.

In [171]:
tensor = torch.tensor([1,2,3])

#tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [172]:
# Move tensor to GPU (if available)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3]), device(type='cpu'))

### 4. Moving tensors back to CPU

In [175]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [177]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [180]:
tensor_on_gpu

tensor([1, 2, 3])

## Exercises & Extra-curriculum

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises